#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# register_page:
#     path: /register
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#     defaults:
#        template: 'pages/register.html.twig'