#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# admin_page:
#     path: /admin/message
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#     defaults:
#        template: 'pages/admin_dash.html.twig'